# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c138fe2d3a95d4fb7223d74ef99aeb601832452339cbc4b3942cedf85fb6fda6fa5cbce014e7f16ad524dbeee6c2a67969366f500cf267be744918f1faba12d

test:
  secret_key_base: ca89e8883a38b75ac03beb7ccfde89611675a4a0370ffdb4bd485c8d816bb8e6a6237d83e1a7c335f6112541cd05ce6733ee0f5a8366e80eb0966e33cf7e33d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
